apiVersion: v1
kind: Namespace
metadata:
  name:  wikiGroup  # <- Reemplaza con el namespace que quieras usar

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wikiGroup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikiGroup
  template:
    metadata:
      labels:
        app: wikiGroup
    spec:
      containers:
        - name: backend
          image: ghcr.io/${MateoMoreno2004}/backend:latest   # <- IMAGEN PUBLICADA EN GHCR
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: wikiGroup
spec:
  selector:
    app: wikiGroup
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: wikiGroup
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public   # <- en MicroK8s normalmente es "public" (verifica con `kubectl get ingressclass`)
  rules:
    - host: 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
