name: Build and Deploy with MicroK8s

on:
  push:
    branches: [dev]

env:
  IMAGE_TAG: ${{ github.event.inputs.image_tag || 'latest' }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run tests with H2
      run: ./mvnw clean test -Dspring.profiles.active=test

  build-and-publish:
    name: Build and Push Image to GHCR
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: read
      packages: write

    steps:
    - name: Mostrar rama actual
      run: "echo 'Rama actual: ${{ github.ref }}'"

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase owner
      run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -f Dockerfile -t ghcr.io/${OWNER_LC}/backend:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${OWNER_LC}/backend:latest

    - name: Print pushed image URL
      run: "echo 'Imagen publicada: ghcr.io/${OWNER_LC}/backend:latest'"


  deploy-onpremise:
    name: Deploy on MicroK8s On-Premise
    runs-on: self-hosted 
    needs: build-and-publish

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Create namespace if not exists
      run: sudo microk8s kubectl create namespace wikigroup --dry-run=client -o yaml | sudo microk8s kubectl apply -f -
    - name: Apply Kubernetes deployment
      run: sudo microk8s kubectl apply -f K8s/k8s.yaml
    - name: Restart Kubernetes deployment
      run: sudo microk8s kubectl rollout restart deployment/backend -n wikigroup